### ISSUE TITLE
Trained network

### ISSUE THREAD

**Issue by Celli119** [MASILab/EssNet#1]
Are you allowed to share the trained weights and could you provide it?

**Comment by MalindaVania** [comment]
Hi, I would like to train my own dataset, and I checked the data structure in sublist. But it seems like there are some missing information how to structure the folder data. Could you please share the information about it? Did you make the 3 folder for the data? MRI data, CT data and the MRI Label data?

**Comment by yuankaihuo** [comment]
> Are you allowed to share the trained weights and could you provide it?

It would be difficult to share the weight due to the IP issue. But I will try. Thanks

**Comment by yuankaihuo** [comment]
> Hi, I would like to train my own dataset, and I checked the data structure in sublist. But it seems like there are some missing information how to structure the folder data. Could you please share the information about it? Did you make the 3 folder for the data? MRI data, CT data and the MRI Label data?

Thanks for your questions. 
You can see the subject list files, it will show you the structure that I used.
https://github.com/MASILab/SynSeg-Net/tree/master/sublist
